services:
  bot:
    build: .
    container_name: voltic_bot
    restart: unless-stopped
    env_file:
      - .env.production.bot
    networks:
      - voltic_network

networks:
  voltic_network:
    driver: bridge